export default {
    'WELCOME': 'Selamat Datang',
    'TICKETS': 'Tiket',
    'ARTIKEL': 'Artikel',
    'ACCOUNT': 'Account',
    'SUBMIT': 'Kirim',
    'EMAIL': 'Email',
    'PASSWORD': 'Kata Sandi',
    'REPEAT_PASSWORD': 'Ulangi kata sandi',
    'LOG_IN': 'Log in',
    'SIGN_UP': 'Daftar',
    'FORGOT_PASSWORD': 'Lupa kata sandi Anda?',
    'RECOVER_PASSWORD': 'Ganti kata sandi',
    'RECOVER_SENT': 'Email dengan instruksi pemulihan telah dikirim.',
    'NEW_EMAIL': 'Email baru',
    'FULL_NAME': 'Nama lengkap',
    'OLD_PASSWORD': 'Kata sandi lama'
    'NEW_PASSWORD': 'Kata sandi baru',
    'REPEAT_NEW_PASSWORD': 'Ulangi kata sandi baru',
    'BACK_LOGIN_FORM': 'Kembali ke form login',
    'VIEW_ARTICLES': 'Lihat Artikel',
    'EDIT_PROFILE': 'Edit Profil',
    'CLOSE_SESSION': 'Close session',
    'CREATE_TICKET': 'Buat Tiket',
    'TICKET_LIST': 'Daftar Tiket'
    'SUPPORT_CENTER': 'Support Center',
    'DEPARTEMENT': 'Departement',
    'AUTHOR': 'Author',
    'DATE': 'Date',
    'RESPOND': 'Respond',
    'RESPOND_TICKET': 'Respond Ticket',
    'NO_ATTACHMENT': 'Tidak ada lampiran file',
    'STAFF': 'Staf',
    'CUSTOMER': 'Customer',
    'YES': 'Ya',
    'NO': 'Tidak',
    'CANCEL': 'Batal',
    'MY_ACCOUNT': 'Akun Saya',
    'DASHBOARD': 'Dashboard',
    'USERS': 'Pengguna',
    'SETTINGS': 'Pengaturan',
    'STATISTICS': 'Statistik',
    'LAST_ACTIVITY': 'Aktivitas Terakhir',
    'MY_TICKETS': 'Tiket Saya',
    'NEW_TICKETS': 'Tiket Baru',
    'ALL_TICKETS': 'Semua Tiket',
    'CUSTOM_RESPONSES': 'Respon Khusus',
    'LIST_USERS': 'Daftar Pengguna',
    'BAN_USERS': 'Pengguna yang dilarang'
    'LIST_ARTICLES': 'Daftar Artikel'
    'STAFF_MEMBERS': 'Anggota Staf',
    'DEPARTEMEN': 'Departemen'
    'SYSTEM_PREFERENCES': 'System Preferences',
    'ADVANCED_SETTINGS': 'Advanced Settings',
    'EMAIL_TEMPLATES': 'Template Email',
    'FILTERS_CUSTOM_FIELDS': 'Filters and Custom Fields',
    'PRIORITY': 'Prioritas',
    'NUMBER': 'Nomor',
    'HIGH': 'High',
    'MEDIUM': 'Medium',
    'LOW': 'Low',
    'TITLE': 'Judul',
    'CONTENT': 'Konten',
    'SAVE': 'Simpan',
    'DISCARD_CHANGES': 'Buang perubahan',
    'DELETE': 'Hapus',
    'LANGUAGE': 'Bahasa',
    'OWNER': 'Owner',
    'OWNED': 'Owned',
    'STATUS': 'Status',
    'NONE': 'Tidak ada',
    'OPENED': 'Dibuka',
    'CLOSED': 'Tertutup',
    'CLOSE': 'Tutup',
    'RE_OPEN': 'Kembali dibuka',
    'ASSIGN_TO_ME': 'Tetapkan ke saya',
    'UN_ASSIGN': 'Batal tetapkan',
    'VIEW_TICKET': 'View Ticket',
    'VIEW_TICKET_DESCRIPTION': 'Periksa status tiket Anda dengan menggunakan nomor tiket dan email Anda.',
    'SELECT_CUSTOM_RESPONSE': 'Pilih respons khusus ...',
    'WARNING': 'Peringatan',
    'INFO': 'Informasi',
    'ALL_DEPARTMENTS': 'Semua Departemen',
    'EMAIL_BANNED': 'Email banned',
    'UN_BAN': 'Disable ban',
    'BAN_NEW_EMAIL': 'Ban new email',
    'BAN_EMAIL': 'Ban email',
    'EDIT_EMAIL': 'Edit email',
    'EDIT_PASSWORD': 'Edit kata sandi',
    'CHANGE_EMAIL': 'Ubah email',
    'CHANGE_PASSWORD': 'Ubah kata sandi',
    'NAMA': 'Nama',
    'SIGNUP_DATE': 'Tanggal daftar',
    'SEARCH_USERS': 'Cari pengguna ...',
    'SEARCH_EMAIL': 'Cari email ...',
    'USER_VIEW_TITLE': 'User # {userId}',
    'EDIT_TOPIC': 'Edit Topic',
    'ADD_TOPIC': 'Add Topic',
    'ICON': ​​'Ikon',
    'COLOR': 'Warna',
    'ADD_NEW_ARTICLE': 'Tambahkan artikel baru',
    'ADD_ARTICLE': 'Tambahkan artikel',
    'LAST_EDITED_IN': 'Terakhir diedit pada {date}',
    'EDIT': 'Edit',
    'NO_RESULTS': 'Tidak ada hasil',
    'DELETE_AND_BAN': 'Hapus dan Larangan',
    'STAFF_LEVEL': 'Tingkat Staf',
    'ASSIGNED': 'Assigned',
    'ASSIGNED_TICKETS': '{tickets} assigned tickets',
    'CLOSED_TICKETS': '{tickets} closed tickets',
    'LAST_LOGIN': 'Login terakhir',
    'ADD_NEW_STAFF': 'Tambah staf baru',
    'ADD_STAFF': 'Tambah staf'
    'LEVEL': 'Level',
    'LEVEL_1': 'Level 1 (Tiket)',
    'LEVEL_2': 'Level 2 (Tiket + Artikel)',
    'LEVEL_3': 'Level 3 (Tiket + Artikel + Staf)',
    'LEVEL_1_DESCRIPTION': 'hanya dapat menanggapi tiket dan mengelola pengguna.',
    'LEVEL_2_DESCRIPTION': 'dapat melakukan setiap Level 1, dapat membuat atau mengedit artikel dan bisa membuat tanggapan khusus.',
    'LEVEL_3_DESCRIPTION': 'dapat melakukan setiap Level 2, dapat membuat atau mengedit anggota staf dan dapat mengelola keseluruhan sistem.',
    'UPDATE_EMAIL': 'Perbarui email',
    'UPDATE_PASSWORD': 'Perbarui kata sandi',
    'UPDATE_LEVEL': 'Perbarui level',
    'UPDATE_DEPARTMENTS': 'Perbarui departemen',
    'EDIT_STAFF': 'Edit anggota staf',
    'ADD_DEPARTMENT': 'Tambahkan departemen',
    'UPDATE_DEPARTMENT': 'Perbarui departemen',
    'TRANSFER_TICKETS_TO': 'Transfer tiket ke',
    'COMMENTS': 'Komentar',
    'DELETE_STAFF_MEMBER': 'Hapus anggota staf',
    'MAINTENANCE_MODE': 'Maintenance mode',
    'MAINTENANCE_MODE_INFO': 'It will temporary disable the system for regular users.',
    'RECOVER_DEFAULT': 'Recover default',
    'SUPPORT_CENTER_URL': 'Support Center URL',
    'SUPPORT_CENTER_TITLE': 'Support Center Title',
    'SUPPORT_CENTER_LAYOUT': 'Support Center Layout',
    'DEFAULT_TIMEZONE': 'Default Timezone (GMT)',
    'NOREPLY_EMAIL': 'Noreply Email',
    'SMTP_USER': 'SMTP User',
    'SMTP_SERVER': 'SMTP Server',
    'SMTP_PASSWORD': 'SMTP Password',
    'PORT': 'Port',
    'RECAPTCHA_PUBLIC_KEY': 'Recaptcha Public Key',
    'RECAPTCHA_PRIVATE_KEY': 'Recaptcha Private Key',
    'ALLOW_FILE_ATTACHMENTS': 'Allow file attachments',
    'MAX_SIZE_KB': 'Max Size (KB)',
    'UPDATE_SETTINGS': 'Update settings',
    'DEFAULT_LANGUAGE': 'Default Language',
    'SUPPORTED_LANGUAGES': 'Supported Languages',
    'SUPPORTED_LANGUAGES_INFO': 'Supported languages are the languages that tickets can be written in.',
    'ALLOWED_LANGUAGES': 'Allowed Languages',
    'ALLOWED_LANGUAGES_INFO': 'Allowed languages are the languages that can be used by an user.',
    'SETTINGS_UPDATED': 'Settings have been updated',
    'ON': 'On',
    'OFF': 'Off',
    'BOXED': 'Boxed',
    'FULL_WIDTH': 'Full width',
    'LOAD_MORE': 'Load More',
    'MY_NOTIFICATIONS': 'My notifications',
    'ALL_NOTIFICATIONS': 'All notifications',
    'VERIFY_SUCCESS': 'User verified',
    'VERIFY_FAILED': 'Could not verify',
    'ENABLE_USER_SYSTEM': 'Use user system for customers',
    'ENABLE_USER_REGISTRATION': 'Enable user registration',
    'INCLUDE_USERS_VIA_CSV': 'Include users via CSV file',
    'BACKUP_DATABASE': 'Backup database',
    'DELETE_ALL_USERS': 'Delete all users',
    'PLEASE_CONFIRM_PASSWORD': 'Please confirm your password to make these changes',
    'REGISTRATION_API_KEYS': 'Registration API keys',
    'NAME_OF_KEY': 'Name of key',
    'KEY': 'Key',
    'ADD_API_KEY': 'Add API Key',
    'NO_KEY_SELECTED': 'No Key selected',
    'CHECK_TICKET': 'Check Ticket',
    'ACTIVITY': 'Activity',
    'HOME': 'Home',
    'TICKET_NUMBER': 'Ticket number',
    'NEXT': 'Next',
    'SEND_EMAIL_ON_NEW_TICKET': 'Send email on new ticket',
    'STAFF_UPDATED': 'Staff member has been updated',
    'UPDATE': 'Update',
    'NEVER': 'Never',
	
	'CHART_CREATE_TICKET': 'Tickets created',
    'CHART_CLOSE': 'Tickets closed',
    'CHART_SIGNUP': 'Signups',
    'CHART_COMMENT': 'Replies',
    'CHART_ASSIGN': 'Assigned',

    //ACTIVITIES
    'ACTIVITY_COMMENT': 'commented ticket',
    'ACTIVITY_ASSIGN': 'assigned ticket',
    'ACTIVITY_UN_ASSIGN': 'unassigned ticket',
    'ACTIVITY_CLOSE': 'closed ticket',
    'ACTIVITY_CREATE_TICKET': 'created ticket',
    'ACTIVITY_RE_OPEN': 'reopened ticket',
    'ACTIVITY_DEPARTMENT_CHANGED': 'changed department of ticket',
    'ACTIVITY_PRIORITY_CHANGED': 'changed priority of ticket',

    'ACTIVITY_EDIT_SETTINGS': 'edited settings',
    'ACTIVITY_SIGNUP': 'signed up',
    'ACTIVITY_ADD_TOPIC': 'added topic',
    'ACTIVITY_ADD_ARTICLE': 'added article',
    'ACTIVITY_DELETE_TOPIC': 'deleted topic',
    'ACTIVITY_DELETE_ARTICLE': 'deleted article',
    'ACTIVITY_EDIT_ARTICLE': 'edited article',
    'ACTIVITY_ADD_STAFF': 'added staff',
    'ACTIVITY_ADD_DEPARTMENT': 'added department',
    'ACTIVITY_DELETE_DEPARTMENT': 'deleted department',
    'ACTIVITY_EDIT_DEPARTMENT': 'edited department',
    'ACTIVITY_ADD_CUSTOM_RESPONSE': 'added custom response',
    'ACTIVITY_DELETE_CUSTOM_RESPONSE': 'deleted custom response',
    'ACTIVITY_EDIT_CUSTOM_RESPONSE': 'edited custom response',
    'ACTIVITY_BAN_USER': 'banned user',
    'ACTIVITY_DELETE_USER': 'deleted user',
    'ACTIVITY_UN_BAN_USER': 'unbanned user',

    'SERVER_REQUIREMENTS': 'Server requirements',
    'DATABASE_CONFIGURATION': 'Database configuration',
    'ADMIN_SETUP': 'Admin setup',
    'COMPLETED': 'Completed',
    'INSTALL_HEADER_TITLE': 'OpenSupports Installation Wizard',
    'INSTALL_HEADER_DESCRIPTION': 'This wizard will help you to configure and install OpenSupports on your website',
    'SELECT_LANGUAGE': 'Select language',
    'REQUIREMENT': 'Requirement',
    'VALUE': 'Value',
    'REFRESH': 'Refresh',
    'USER_SYSTEM': 'User System',
    'PREVIOUS': 'Previous',
    'DATABASE_HOST': 'MySQL server',
    'DATABASE_NAME': 'MySQL database name',
    'DATABASE_USER': 'MySQL user',
    'DATABASE_PASSWORD': 'MySQL password',
    'ADMIN_NAME': 'Admin account name',
    'ADMIN_EMAIL': 'Admin account email',
    'ADMIN_PASSWORD': 'Admin account password',
    'ADMIN_PASSWORD_DESCRIPTION': 'Please remember this password. It is needed for accessing the admin panel. You can change it later.',
    'INSTALLATION_COMPLETED': 'Installation completed.',
    'INSTALLATION_COMPLETED_DESCRIPTION': 'The installation of OpenSupports is completed. Redirecting to admin panel...',

    'STEP_TITLE': 'Step {current} of {total} - {title}',
    'STEP_1_DESCRIPTION': 'Select your preferred language for the installation wizard.',
    'STEP_2_DESCRIPTION': 'Here are listed the requirements for running OpenSupports. Please make sure that all requirements are satisfied.',
    'STEP_3_DESCRIPTION': 'Please fill the MySQL database configuration.',
    'STEP_4_DESCRIPTION': 'Please select your user system preferences.',
    'STEP_5_DESCRIPTION': 'Please fill your general system preferences.',
    'STEP_6_DESCRIPTION': 'Please configure the administrator account.',
    'STEP_7_DESCRIPTION': 'Installation is completed.',

    //VIEW DESCRIPTIONS
    'CREATE_TICKET_DESCRIPTION': 'This is a form for creating tickets. Fill the form and send us your issues/doubts/suggestions. Our support system will answer it as soon as possible.',
    'TICKET_LIST_DESCRIPTION': 'Here you can find a list of all tickets you have sent to our support team.',
    'TICKETS_DESCRIPTION': 'Send ticket through our support center and get response of your doubts, suggestions and issues.',
    'ARTICLES_DESCRIPTION': 'Take a look to our articles about common issues, guides and documentation.',
    'ACCOUNT_DESCRIPTION': 'All your tickets are stored in your account\'s profile. Keep track of all your tickets you send to our staff team.',
    'SUPPORT_CENTER_DESCRIPTION': 'Welcome to our support center. You can contact us through a tickets system. Your tickets will be answered by our staff.',
    'CUSTOM_RESPONSES_DESCRIPTION': 'Custom responses are automated responses for common problems',
    'MY_TICKETS_DESCRIPTION': 'Here you can view the tickets you are responsible for.',
    'NEW_TICKETS_DESCRIPTION': 'Here you can view all the new tickets that are not assigned by anyone.',
    'ALL_TICKETS_DESCRIPTION': 'Here you can view the tickets of the departments you are assigned.',
    'TICKET_VIEW_DESCRIPTION': 'This ticket has been sent by a customer. Here you can respond or assign the ticket',
    'BAN_USERS_DESCRIPTION': 'Here you can see a list of banned emails, you can un-ban them or add more emails to the list.',
    'LIST_USERS_DESCRIPTION': 'This is the list of users that are registered in this platform. You can search for someone in particular, delete it or ban it.',
    'USER_VIEW_DESCRIPTION': 'Here you can find all the information about an user and all the tickets sent by the user. You can also delete or ban it.',
    'DELETE_USER_DESCRIPTION': 'The user will not be able to log in aging and all its tickets will be erased. Also, the email can not be used any more.',
    'DELETE_TOPIC_DESCRIPTION': 'By deleting the topic, all articles on it will be erased.',
    'EDIT_TOPIC_DESCRIPTION': 'Here you can change the name, the icon and the icon color of the topic.',
    'ADD_ARTICLE_DESCRIPTION': 'Here you can add an article that will be available for every user. It will be added inside the category {category}.',
    'LIST_ARTICLES_DESCRIPTION': 'This is a list of articles that includes information about our services.',
    'ADD_TOPIC_DESCRIPTION': 'Here you can add a topic that works as a category for articles.',
    'DELETE_ARTICLE_DESCRIPTION': 'You\'re going to delete this article forever.',
    'STAFF_MEMBERS_DESCRIPTION': 'Here you can see who are your staff members.',
    'ADD_STAFF_DESCRIPTION': 'Here you can add staff members to your teams.',
    'EDIT_STAFF_DESCRIPTION': 'Here you can edit information about a staff member.',
    'MY_ACCOUNT_DESCRIPTION': 'Here you can edit information about you.',
    'DEPARTMENTS_DESCRIPTION': 'A department is a group where the tickets can go. They are used to categorize the tickets. You can assign them to other staff members.',
    'MAINTENANCE_MODE_DESCRIPTION': 'The support system is in maintenance mode, thus unavailable at the moment. We will come back as soon as possible.',
    'EMAIL_TEMPLATES_DESCRIPTION': 'Here you can edit the templates of the emails that will be sent to users. Remember that the double brackets curly braces indicate a variable value. For example, \'name\' represents the user\'s name.',
    'SYSTEM_PREFERENCES_DESCRIPTION': 'Here you can edit the preferences of the system.',
    'VERIFY_SUCCESS_DESCRIPTION': 'You user has been verified correctly. You can log in now.',
    'VERIFY_FAILED_DESCRIPTION': 'The verification could not be done.',
    'STATISTICS_DESCRIPTION': 'Here you can view statistics related to tickets and signups.',
    'ADVANCED_SETTINGS_DESCRIPTION': 'Here you can change the advanced settings of your system. Please be careful, the changes you make can not be reversed.',
    'USER_SYSTEM_DISABLED': 'User system has been disabled',
    'USER_SYSTEM_ENABLED': 'User system has been enabled',
    'REGISTRATION_DISABLED': 'Registration has been disabled',
    'REGISTRATION_ENABLED': 'Registration has been enabled',
    'ADD_API_KEY_DESCRIPTION': 'Insert the name and a registration api key will be generated.',
    'SIGN_UP_VIEW_DESCRIPTION': 'Here you can create an account for our support center. It is required for send tickets and see documentation.',
    'EDIT_PROFILE_VIEW_DESCRIPTION': 'Here you can edit your user by changing your email or your password.',
    'ENABLE_USER_SYSTEM_DESCRIPTION': 'Enable/disable the use of an user system. If you disable it, all users will be deleted but the tickets will be kept. If you enable it, the users of existent tickets will be created.',
    'CSV_DESCRIPTION': 'The CSV file must have 3 columns: email, password, name. There is no limit in row count. It will be created one user per row in the file.',
    'SMTP_SERVER_DESCRIPTION': 'The configuration of the SMTP server allows the application to send mails. If you do not configure it, no emails will be sent by OpenSupports.',

    //ERRORS
    'EMAIL_OR_PASSWORD': 'Email or password invalid',
    'EMAIL_NOT_EXIST': 'Email does not exist',
    'ERROR_EMPTY': 'Invalid value',
    'ERROR_PASSWORD': 'Invalid password',
    'ERROR_NAME': 'Invalid name',
    'ERROR_TITLE': 'Invalid title',
    'ERROR_EMAIL': 'Invalid email',
    'ERROR_CONTENT_SHORT': 'Content too short',
    'PASSWORD_NOT_MATCH': 'Password does not match',
    'INVALID_RECOVER': 'Invalid recover data',
    'TICKET_SENT_ERROR': 'An error occurred while trying to create the ticket.',
    'TICKET_COMMENT_ERROR': 'An error occurred while trying to add the comment.',
    'NO_PERMISSION': 'You\'ve no permission to access to this page.',
    'INVALID_USER': 'User id is invalid',
    'ERROR_RETRIEVING_TICKETS': 'An error occurred while trying to retrieve tickets.',
    'ERROR_RETRIEVING_USERS': 'An error occurred while trying to retrieve users.',
    'ERROR_RETRIEVING_BAN_LIST': 'An error occurred while trying to retrieve the list of banned emails.',
    'ERROR_BANNING_EMAIL': 'An error occurred while trying to ban the email.',
    'ERROR_RETRIEVING_ARTICLES': 'An error occurred while trying to retrieve articles.',
    'ERROR_LIST': 'Select at least one',
    'ERROR_URL': 'Invalid URL',
    'UNVERIFIED_EMAIL': 'Email is not verified yet',
    'ERROR_UPDATING_SETTINGS': 'An error occurred while trying to update settings',
    'INVALID_EMAIL_OR_TICKET_NUMBER': 'Invalid email or ticket number',
    'INVALID_FILE': 'Invalid file',
    'ERRORS_FOUND': 'Errors found',

    //MESSAGES
    'SIGNUP_SUCCESS': 'You have registered successfully in our support system.',
    'TICKET_SENT': 'Ticket has been created successfully.',
    'VALID_RECOVER': 'Password recovered successfully',
    'EMAIL_EXISTS': 'Email already exists',
    'ARE_YOU_SURE': 'Confirm action',
    'EMAIL_WILL_CHANGE': 'The current email will be changed',
    'PASSWORD_WILL_CHANGE': 'The current password will be changed',
    'EMAIL_CHANGED': 'Email has been changed successfully',
    'PASSWORD_CHANGED': 'Password has been changed successfully',
    'OLD_PASSWORD_INCORRECT': 'Old password is incorrect',
    'WILL_LOSE_CHANGES': 'You haven\'t save. Your changes will be lost.',
    'WILL_DELETE_CUSTOM_RESPONSE': 'The custom response will be deleted.',
    'WILL_DELETE_DEPARTMENT': 'The department will be deleted. All the tickets will be transfer to the department selected.',
    'NO_STAFF_ASSIGNED': 'No staff member is assigned to this department.',
    'LEVEL_UPDATED': 'Level has been updated successfully.',
    'DEPARTMENTS_UPDATED': 'Departments have been updated successfully.',
    'FAILED_EDIT_STAFF': 'An error occurred while trying to edit staff member.',
    'EMAIL_BANNED_SUCCESSFULLY': 'Email has been banned successfully',
    'WILL_DELETE_STAFF': 'This staff member will be deleted and all its tickets will be unassigned.',
    'WILL_RECOVER_EMAIL_TEMPLATE': 'This email template will be recover to it\'s default value on this language.',
    'SUCCESS_IMPORTING_CSV_DESCRIPTION': 'CSV File has been imported successfully',
    'SUCCESS_DELETING_ALL_USERS': 'Users have beend deleted successfully',

    'LAST_7_DAYS': 'Last 7 days',
    'LAST_30_DAYS': 'Last 30 days',
    'LAST_90_DAYS': 'Last 90 days',
    'LAST_365_DAYS': 'Last 365 days',

    'ACTIVITY_COMMENT_THIS': 'commented this ticket',
    'ACTIVITY_ASSIGN_THIS': 'assigned this ticket',
    'ACTIVITY_UN_ASSIGN_THIS': 'unassigned this ticket',
    'ACTIVITY_CLOSE_THIS': 'closed this ticket',
    'ACTIVITY_CREATE_TICKET_THIS': 'created this ticket',
    'ACTIVITY_RE_OPEN_THIS': 'reopened this ticket',
    'ACTIVITY_DEPARTMENT_CHANGED_THIS': 'changed department of this ticket to ',
    'ACTIVITY_PRIORITY_CHANGED_THIS': 'changed priority of this ticket to',
    'DATE_PREFIX': 'on',
    'LEFT_EMPTY_DATABASE': 'Leave empty for automatic database creation',
    'REMEMBER_ME': 'Remember me',
    'EMAIL_LOWERCASE': 'email',
    'PASSWORD_LOWERCASE': 'password',
    'TEST_SMTP_CONNECTION': 'Test SMTP connection',
    'SMTP_CONNECTION_SUCCESS': 'SMTP credentials are valid.',
    'SMTP_CONNECTION_ERROR': 'Can\'t connect to SMTP server.'
};
